/**
 * Export utilities for log highlighter output.
 *
 * All exports are generated entirely client-side using the
 * Blob API and URL.createObjectURL(). No server involved.
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export type ExportFormat = 'html' | 'text'

export type ExportResult =
  | { ok: true }
  | { ok: false; reason: string }

// ─── HTML Export ─────────────────────────────────────────────────────────────

/**
 * Generates a complete, self-contained HTML file from highlighted log output.
 *
 * The generated file:
 *   - Has no external dependencies (no CDN, no fonts, no scripts)
 *   - Preserves all span color styles inline
 *   - Works offline when opened in any browser
 *   - Has a dark background matching the tool's output
 *   - Includes metadata (export timestamp, line count)
 *
 * @param highlightedHtml - The innerHTML string from the output panel
 * @param rawInput - The original raw log text (used for metadata)
 * @returns ExportResult
 */
export function exportAsHtml(highlightedHtml: string, rawInput: string): ExportResult {
  if (!highlightedHtml || highlightedHtml.trim() === '') {
    return { ok: false, reason: 'Nothing to export — output is empty.' }
  }

  try {
    const lineCount = (rawInput.match(/\n/g) ?? []).length + 1
    const exportedAt = new Date().toISOString()
    const byteSize = new Blob([rawInput]).size
    const sizeStr = byteSize < 1024
      ? `${byteSize} B`
      : `${(byteSize / 1024).toFixed(1)} KB`

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Log Export — ${exportedAt}</title>
  <style>
    /* Reset */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      background: #0d0d0d;
      color: #e0e0e0;
      font-family: 'Cascadia Code', 'Fira Code', 'JetBrains Mono', 'Consolas', 'Monaco', monospace;
      font-size: 13px;
      line-height: 1.6;
      padding: 0;
    }

    header {
      background: #141414;
      border-bottom: 1px solid #2a2a2a;
      padding: 14px 24px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      flex-wrap: wrap;
      gap: 8px;
    }

    header h1 {
      font-size: 13px;
      color: #888;
      font-weight: normal;
    }

    header .meta {
      font-size: 11px;
      color: #555;
    }

    main {
      padding: 20px 24px;
      overflow-x: auto;
    }

    pre {
      white-space: pre-wrap;
      word-break: break-all;
      line-height: 1.65;
    }

    /* Line numbers */
    .line {
      display: flex;
      min-height: 1.65em;
    }

    .line-number {
      user-select: none;
      color: #333;
      min-width: 48px;
      padding-right: 20px;
      text-align: right;
      flex-shrink: 0;
      border-right: 1px solid #1e1e1e;
      margin-right: 16px;
    }

    .line-content {
      flex: 1;
      white-space: pre-wrap;
      word-break: break-all;
    }

    footer {
      padding: 12px 24px;
      border-top: 1px solid #1a1a1a;
      font-size: 11px;
      color: #333;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <h1>Log Export</h1>
    <span class="meta">
      ${lineCount.toLocaleString()} lines · ${sizeStr} · exported ${exportedAt}
    </span>
  </header>
  <main>
    <pre>${wrapLinesWithNumbers(highlightedHtml)}</pre>
  </main>
  <footer>
    Generated by Log Highlighter
  </footer>
</body>
</html>`

    downloadFile(html, `log-export-${formatDateForFilename()}.html`, 'text/html;charset=utf-8')
    return { ok: true }
  } catch {
    return { ok: false, reason: 'Failed to generate HTML export. Please try again.' }
  }
}

// ─── Plain Text Export ────────────────────────────────────────────────────────

/**
 * Downloads the raw log input as a plain .txt file.
 * Strips any processing artifacts — returns exactly what the user pasted.
 *
 * @param rawInput - The original raw log text from the textarea
 * @returns ExportResult
 */
export function exportAsText(rawInput: string): ExportResult {
  if (!rawInput || rawInput.trim() === '') {
    return { ok: false, reason: 'Nothing to export — input is empty.' }
  }

  try {
    downloadFile(rawInput, `log-export-${formatDateForFilename()}.txt`, 'text/plain;charset=utf-8')
    return { ok: true }
  } catch {
    return { ok: false, reason: 'Failed to generate text export. Please try again.' }
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Triggers a file download in the browser using a temporary anchor element.
 *
 * @param content - The file content string
 * @param filename - The suggested filename for the download
 * @param mimeType - The MIME type of the file
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)

  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.style.display = 'none'

  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)

  // Revoke object URL after a short delay to allow download to start
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

/**
 * Formats current date as YYYY-MM-DD_HH-MM for use in filenames.
 */
function formatDateForFilename(): string {
  const now = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}_${pad(now.getHours())}-${pad(now.getMinutes())}`
}

/**
 * Wraps each line of highlighted HTML in a div with a line number.
 * Input is the raw innerHTML which uses \n as line separator.
 *
 * @param highlightedHtml - The full innerHTML of the output panel
 * @returns HTML string with each line wrapped in .line divs
 */
function wrapLinesWithNumbers(highlightedHtml: string): string {
  const lines = highlightedHtml.split('\n')
  return lines
    .map((lineHtml, index) => {
      const lineNum = index + 1
      return `<div class="line"><span class="line-number">${lineNum}</span><span class="line-content">${lineHtml || '&nbsp;'}</span></div>`
    })
    .join('')
}